name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.config_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - config_name: ubuntu-22.04
            os: ubuntu-22.04
          - config_name: ubuntu-22.04 with optional dependencies
            os: ubuntu-22.04
            install_optional_dependencies: true
            dist_install_and_test: true
            test_with_sudo: true
          - config_name: ubuntu-24.04
            os: ubuntu-24.04
          - config_name: macos-13
            os: macos-13
          - config_name: macos-14
            os: macos-14
          - config_name: macos-15
            os: macos-15
          - config_name: windows-latest
            os: windows-latest
            install_optional_dependencies: true
            dist_install_and_test: true

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          show-progress: false
      - run: |
          apk update -q && apk add -q perl
        if: startsWith(matrix.image, 'alpine:')
      - run: |
          apt-get update -q && apt-get install -qy perl
        if: startsWith(matrix.image, 'debian:')
      - run: |
          dnf update --quiet -y && dnf install --quiet -y perl
        if: startsWith(matrix.image, 'fedora:')
      - uses: eserte/Doit/.github/actions/install-doit-from-github@master
      - name: Test
        run: |
          prove -l -j8 t

  test_in_container:
    name: Test with ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: perl:5.8.9-threaded-stretch
          - image: perl:5.10.1-buster
          - image: perl:5.12.5-stretch
          - image: perl:5.14.4-stretch
          - image: perl:5.16.3-buster
          - image: perl:5.18.4-buster
          - image: perl:5.22.4-stretch
          - image: perl:5.36.0-slim-bullseye
          - image: perl:5.38.0-slim-bookworm
          - image: perl:5.40.0-slim-bookworm
          ## use debian:* images only if there's no suitable perl:* image
          #- image: debian:bookworm
          ## ubuntu:focal not enabled, need to install full perl with prove first
          #- image: ubuntu:focal

    steps:
      # Note: checkout@v4 does not work with older debians (e.g.stretch), so do this step *outside* the container
      - uses: actions/checkout@v4
      - uses: eserte/Doit/.github/actions/install-doit-from-github@master
      - name: Test
        run: |
          docker run --quiet -e PERL5LIB=$GITHUB_WORKSPACE/Doit/lib -v $(pwd):$(pwd) ${{ matrix.image }} sh -c "cd $(pwd); "'
            export HARNESS_TIMER=1 HARNESS_OPTIONS=j8
            prove -l t
          '
